drop table OPINIONEWS;
CREATE TABLE OPINIONEWS(
id INT NOT NULL AUTO_INCREMENT, 
PRIMARY KEY(id),
HEADING VARCHAR(3000),
IMAGE_URL VARCHAR(3000),
DEFINITION_DETAILS TEXT,
SOURCE_URL VARCHAR(3000),
SOURCE VARCHAR(3000));

INSERT INTO `OPINIONEWS`(HEADING,IMAGE_URL,DEFINITION_DETAILS,SOURCE_URL,SOURCE) VALUES
  ('Turkish warplane downed by Syria may have crossed border', 'http://news.bbcimg.co.uk/media/images/61093000/jpg/_61093222_61093194.jpg','Turkeys President, Abdullah Gul, has said the Turkish fighter jet shot down by Syrias air defence forces on Friday may have violated Syrian airspace.','www.bbc.com','bbc');

drop table OPINIONEWS_DEMOGRAPHY;
CREATE TABLE OPINIONEWS_DEMOGRAPHY(
id INT NOT NULL AUTO_INCREMENT, 
PRIMARY KEY(id),
OPINIONEWS_ID INT,
DEMOGRAPHY_ID CHAR(2),
DEMOGRAPHY_TYPE VARCHAR(3000),
ACTIVE_FOR_NEWS VARCHAR(2) );

INSERT INTO `OPINIONEWS_DEMOGRAPHY`(OPINIONEWS_ID,DEMOGRAPHY_ID,DEMOGRAPHY_TYPE,ACTIVE_FOR_NEWS) VALUES
  (1 ,'AU','CONTINENT','Y');
 INSERT INTO `OPINIONEWS_DEMOGRAPHY`(OPINIONEWS_ID,DEMOGRAPHY_ID,DEMOGRAPHY_TYPE,ACTIVE_FOR_NEWS) VALUES
  (1 ,'WL','WORLD','Y');
drop table OPINIONEWS_ISSUE;  
  CREATE TABLE OPINIONEWS_ISSUE(
id INT NOT NULL AUTO_INCREMENT, 
PRIMARY KEY(id),
OPINIONEWS_ID INT,
ISSUE_ID INT,
ACTIVE_FOR_ISSUE VARCHAR(2));

INSERT INTO `OPINIONEWS_ISSUE`(OPINIONEWS_ID,ISSUE_ID,ACTIVE_FOR_ISSUE) VALUES
  (1, 1,'Y');
  
  
  DELETE  FROM OPINIONEWS_DEMOGRAPHY where id=2
  
  
  select * from countries where name like '%america%';
